### ISSUE TITLE
Xgraph.ahk is not included

### ISSUE THREAD

**Issue by changhenry2** [Joonikko/Panel#1]
Hi Joonikko,
I found this repository from this webpage: 
[](https://linustechtips.com/main/topic/890723-panel-autohotkey-based-gui-for-common-windows-elements/)
I downloaded the ahk file, but it seems that a file called "Xgraph.ahk" is missing.
Could you upload that file to this repository as well? Thanks!

**Comment by Joonikko** [comment]
Yeah sorry, I had excluded the file from the git repository. Added & fixed. Thank you for reporting!
